node {
    stage('Pull Code') {
        checkout scm
    }

    stage('Build & Test') {
        docker.image('node:lts-buster-slim').inside {
            sh 'npm install'
            sh 'CI=true npm test'
        }
    }
}