pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'react-app-viki'
        CONTAINER_NAME = 'react-app-container'
    }

    stages {
        stage('Pull Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                echo "Cek lokasi file saat ini:"
                sh 'pwd'    
                sh 'ls -la' 
                sh 'docker build -t $DOCKER_IMAGE .'
                sh 'docker run --rm $DOCKER_IMAGE npm test'
            }
        }

        stage('Manual Approval') {
            steps {
                input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker rm -f $CONTAINER_NAME || true"
                    
                    sh "docker run -d -p 3000:3000 --name $CONTAINER_NAME $DOCKER_IMAGE"
                    
                    echo "Aplikasi berhasil dideploy! Bisa diakses di localhost:3000"
                    
                    echo "Menunggu 1 menit sebelum mematikan aplikasi..."
                    sleep time: 1, unit: 'MINUTES'
                    
                    sh "docker stop $CONTAINER_NAME"
                    sh "docker rm $CONTAINER_NAME"
                    echo "Aplikasi telah dimatikan otomatis."
                }
            }
        }
    }
}